# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f819009929e1e757a03f8d58d894040b8e4aa54b3063e6cf79be2f3389c222e7494556040e9848b83767762d1143e6199106ceece865851d83e0cf154fb20156

test:
  secret_key_base: 86d3ff81d7cd474c7db98400921cd358c2d78e7d5d95bc31d644da4ee1a83bf422c61bc5f3b8b5b29a616c29cb729ee022961e574b704d83f71f712998b4dad9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
